# Generated by Django 6.0.3 on 2026-04-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogpostcategory',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='blogpostcategory',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
