# Generated by Django 6.0.3 on 2026-03-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='company_logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logo/'),
        ),
        migrations.AddField(
            model_name='companyinfo',
            name='opening_schedule',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
