# Generated by Django 6.0.3 on 2026-03-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_photo', models.ImageField(blank=True, null=True, upload_to='client_photos/')),
                ('client_name', models.CharField(max_length=100)),
                ('client_position', models.CharField(max_length=100)),
                ('client_star_rating', models.IntegerField(blank=True, null=True)),
                ('testimonial_text', models.TextField()),
            ],
        ),
    ]
