# Generated by Django 6.0.3 on 2026-04-01 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(choices=[('books', 'Books'), ('apps', 'Apps'), ('branding', 'Branding'), ('products', 'Products')], max_length=20)),
                ('item_title', models.CharField(max_length=100)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='portfolio_items/')),
                ('item_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_title', models.CharField(max_length=100)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='portfolio_items/')),
                ('item_description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.portfoliocategory')),
            ],
        ),
    ]
