# Generated by Django 6.0.3 on 2026-04-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_portfoliocategory_productitem_portfolioitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='item_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='item_client',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='item_delivery_date',
            field=models.DateField(auto_created=True, blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='item_project_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
