# Generated by Django 6.0.3 on 2026-04-01 08:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_productitem_item_body_productitem_item_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
