# Generated by Django 6.0.3 on 2026-04-01 09:01

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_alter_productitem_item_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
