# Generated by Django 6.0.3 on 2026-04-07 11:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_productitem_item_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='item_body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
