# Generated by Django 6.0.3 on 2026-04-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_productitem_item_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
